### ISSUE TITLE
Upgrading PostgreSQL database for web3signer from 15 to 16 version preventing database loading

### ISSUE THREAD

**Issue by tomaswest** [eth-educators/eth-docker#1536]
Today I've done ./ethd update and my web3signer refused to load.
The problem was, that PostgreSQL for web3signer was updated from 15 to 16 version, because by default we are using 
PG_DOCKER_TAG=alpine
in .env file.
PostgresSQL refused to load because of incompability.
``2023-09-26 18:30:57.504 UTC [1] FATAL:  database files are incompatible with server
2023-09-26 18:30:57.504 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 15, which is not compatible with this version 16.0.``
I've fixed this by myself just by changing PG_DOCKER_TAG to latest v15 alpine image (15.4-alpine3.18), but I think we need better solution for this.

**Comment by yorickdowne** [comment]
Ah so that's what broke it! Thank you. I have since pinned the version to 15-alpine in default.env as well. I agree that there needs to be a way to upgrade the Postgres version, and bring the DB along. Let's keep this issue open for that.

**Comment by yorickdowne** [comment]
This won't be entirely trivial. Basically we need a container with both 15 and 16, run pg_upgrade, then start 16. See https://github.com/tianon/docker-postgres-upgrade

Need to think a little on how to automate that so that major version upgrades happen automatically, maybe once 16 is on 16.4. This does break the usual UX of users being able to choose a specific tag. I'd need to override that, replace the tag and in the same action do the one-time migration.

**Comment by yorickdowne** [comment]
Needs to work with arm64 and alpine. There's a repo that adds arm64; asked whether they'd consider a PR for alpine.

https://codeberg.org/pat-s/docker-postgres-upgrade/issues/3

**Comment by yorickdowne** [comment]
Migrating to bookworm instead, which is the faster PostgreSQL at any rate.

This should land early 2024 with PostgreSQL 16.2.

**Comment by yorickdowne** [comment]
Migration merged

**Comment by tomaswest** [comment]
I've tested migration from 15 to 16, and can confirm it is working.
Thanks for this feature implementation

**Comment by yorickdowne** [comment]
Glad to hear it! I had run a web3signer on 15 for a month and then tested this, to make sure it would work with a medium-sized DB (1.5 GiB and 10k validators - Holesky). It’s good to get confirmation.

There’s a whole failure handler with dire warnings, because if this fails when the old DB is already removed, there’s a slashing risk. I hope no one ever needs to rely on it, but it’s there.
