### ISSUE TITLE
feature request: add archive node option in ./ethd config

### ISSUE THREAD

**Issue by d1onys1us** [eth-educators/eth-docker#1675]
as i frequently set up archive nodes for rollup nodes, i find myself in a workflow that can be cleaned up:
1. cp default.env .env
2. vim .env -> edit ARCHIVE_NODE=true
3. ./ethd config

i think we could add archive_node as an option in ./ethd config, but maybe this is too niche of a use case and should remain as an environment var. in any case i'd like to request this feature.

**Comment by yorickdowne** [comment]
That's a larger discussion around a proper TUI, maybe using config instead of whiptail. There are a lot of advanced features that aren't exposed through the config dialog.

What we do in production is configure via ansible. That repo is here and may give you some ideas: https://github.com/CryptoManufaktur-io/backend-ansible
