### ISSUE TITLE
./ethd config error response from daemon

### ISSUE THREAD

**Issue by dwampa** [eth-educators/eth-docker#1875]
**How to reproduce** — I followed https://eth-docker.net/Support/SSV/ guide 
`cd ssv-node`
`./ethd config` or `sudo ./ethd config `

**Error log:**
```shell
> sudo ./ethd config
grep: /Users/USERNAME/.profile: No such file or directory
You chose to run on holesky testnet
Your deployment choice is: ssv
Creating password file for encrypted SSV secret key
Password:
Creating encrypted operator private key
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
docker: Error response from daemon: error while creating mount source path '/host_mnt/Users/USERNAME/ssv-node/ssv-config/password.pass': mkdir /host_mnt/Users/USERNAME/ssv-node/ssv-config/password.pass: permission denied.
chown: ./ssv-config/encrypted_private_key.json: No such file or directory
```

The file causing the error from daemon is from ssv-config
https://github.com/eth-educators/eth-docker/blob/38b109efd35bef5916d45d1624cdb7023c74d610/ssv-config/config-sample.yaml#L7

I found a couple of similar-ish issues with permissions such as #1117 and #317. Could this be another case where I need to try with customer Dockerfile?

Let me know if you need more details.

**Comment by yorickdowne** [comment]
Couple comments

`./ethd config` should not be run as `sudo`, though I do have logic in there to detect when that is being done and (hopefully) act correctly

Second, something in my config logic is going very wrong. It should check for `aarch64` and not even offer SSV in that case, because SSV only works on amd64. If you want it on arm64, that is a discussion with the upstream maintainers to publish a multiarch Docker image. See https://hub.docker.com/r/bloxstaking/ssv-node/tags

Can you get me the output of `uname -a` on that machine, please? That'll let me see where I'm going wrong in config.

I am currently doing `elif uname -a | grep -q aarch64; then` to detect arm64

**Comment by dwampa** [comment]
Sure thing, here it is:
`Darwin M2-Air.local 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:19:22 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T8112 arm64`

On a side-note, I also assumed the issue is with arm64 so I did spin up a EC2 instance on amd64. Surprisingly, there were other permission issues on Ubuntu 24.04, but no issues on 22.04. JFYI if anyone will report the same errors.

**Comment by yorickdowne** [comment]
Got it. It’s an m1 Mac, so my aarch64 doesn’t work. I should look for arm64. Hopefully that works on other machines too — maybe I’ll look for either.

ssv on arm64 shouldn’t be offered. Thanks for the report. I’ll fix the config script.
