### ISSUE TITLE
Container crashing

### ISSUE THREAD

**Issue by Sigri44** [eth-educators/eth-docker#512]
Hello,

I have follow the quick start guid for docker.
All steps are good, no errors.

But at launch, the last container say "done", but crashed few seconds after, and logs are empty.

Regards.

<img width="437" alt="Capture d’écran 2022-03-28 à 20 23 17" src="https://user-images.githubusercontent.com/9304947/160462382-61b5f8e1-9fe7-41fe-b863-9fdd3362e805.png">
<img width="1063" alt="Capture d’écran 2022-03-28 à 20 23 01" src="https://user-images.githubusercontent.com/9304947/160462398-ba4eff99-2401-48e8-8280-b2288ab523a8.png">

**Comment by ardevd** [comment]
The container is not crashing. What you're seeing is the intended behavior. 

https://hub.docker.com/r/tianon/true/

The image is typically use in docker-compose setups where, since every container must have an image, even if it's only use for volume dependencies, etc, the `tianon/true` image is used due to it being freakishly small.

**Comment by Sigri44** [comment]
Oh ok thank you so much, I was fooled like a rookie, I didn't know that way, thanks for the tip !

Have a nice day !
