### ISSUE TITLE
Question: lighthouse uses two different volumes to store data

### ISSUE THREAD

**Issue by PabloCastellano** [eth-educators/eth-docker#982]
Hello :wave:

Why does the `lighthouse.yml` docker-compose file defines two volumes `lhbeacon-data` and `lhvalidator-data`?
Both of them are mapped to `/var/lib/lighthouse` and the current size of that directory is 125GB in my node. Isn't it duplicating the same folder in different volumes?

I've been using one volume for both `validator` and `consensus` and works fine but before sending my PR I would like to understand if there is a reason behind using different volumes.

**Comment by yorickdowne** [comment]
It's not duplicating anything. `/var/lib/lighthouse` just exists inside the container. The VC has its own volume separate from the CL so that it's easy to remove the DB and start over without removing keys, and vice versa.

This pattern works for Lighthouse, Lodestar and Prysm. Teku and Nimbus have the VC in the main CL process by default, so there this separation doesn't exist.

You can see the size of volumes with `docker system df -v`
